### ISSUE TITLE
[Mechanics] Effects slowing down cast speed also affect GCD

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#763]
**Description:**

Effects like Mind-Numbing Poison (Item ID: 9186) also slow down Global Cooldown which they shouldn't. 
(They already can't reduce the gcd above 1.5 and that is working)

**Expected behaviour:**

Global Cooldowns should be unaffected by spells like Slow, Mind-Numbing poison effect and Curse of Tongues. It's a known bug across many private servers.

** Reproduce steps:**
- Cast Icy Veins on mage
- Check GCD for an instant spell
- Apply mind numbing on mage
- Check GCD for an instant spell, and see that it has increased

**Some related issues and conclusions:**
https://github.com/ccshiro/cc-buglist/issues/248
(kelno: this bug report is actually about getting above 1.5 and not about this exact problem)

**rev. hash/commit:** 
rev. 10603

**Comment by kelno** [comment]
(from chat)
-- Kelno
We never send the gcd to the client, what we do is
We update the player field UNIT_MOD_CAST_SPEED whenever a buff/debuff is applied
Which is a multiplier, 1 by default
If you get icy veins it gets down to 0.8333 for example
And what this does affect that I can see so far is:
- The GCD
- The shown cast time on tooltips
So I find this very strange
Because changing this would also break the cast time on tooltips
-- Jerry
so two things are controlled by one thing
maybe GCD shouldn't be in UNIT_MOD_CAST_SPEED at all
-- Kelno
Yes, maybe there are more than two but whatever
Ah well that's not something we can control
That's just how the client decides the GCD
-- Jerry
okay, so how did Warmane do it
hmmm
-- Kelno
Maybe they broke the tooltip in that case

**Comment by kelno** [comment]
Apparently it's not the case on warmane either (tested by jerry): 
https://streamable.com/ami5k

Also from blizz dev:
[5:27 PM] Jerry: Hey Alex, I have a pretty specific question. Back in patch 2.4.0 you guys made a change so that Haste affects Global Cooldowns as well (so they get reduced down to 1s for casters). Now, my question is if we have some haste and our GCD is reduced to let's say 1.2 and we get affected by something like Curse of Tongues or Mind-Numbing poison does it get brought back up closer to the original 1.5, or is GCD unaffected and stays at 1.2? Basically, is GCD only affected by positive effects or can it also be affected by negative ones?
[5:31 PM] Xelnath: Both
[5:31 PM] Xelnath: It is net cooldown
[5:32 PM] Jerry: thank you

**Comment by kelno** [comment]
Conclusion here is: It should be affected.
